#FIXME change file name to actual app name
#FIXME change to actual app name
name: $hype_ballsort_app

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: hyoo-ru/mam_build@master2
      with:
        package: 'hype/ballsort' #FIXME namespace of this package
        modules: 'app' #FIXME which modules to build, remove line if only on module at the root
    
    #FIXME remove one of the following
        
    - uses: hyoo-ru/gh-deploy@v4.4.1
      if: github.ref == 'refs/heads/master'
      with:
        folder: 'hype/ballsort/app/-' #FIXME path to build app
